-- V10: Sequences required by Hibernate for maternity tables

CREATE SEQUENCE IF NOT EXISTS pregnancies_SEQ
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS anc_visits_SEQ
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS maternity_admissions_SEQ
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS deliveries_SEQ
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS baby_records_SEQ
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS postnatal_visits_SEQ
    START WITH 1 INCREMENT BY 50;